site_name: ak-rpi
repo_url: https://github.com/szvsw/ak-rpi
site_url: https://szvsw.github.io/ak-rpi
site_description: This is a repository for synchronizing Raspberry Pis with AccessKit.
site_author: Sam Wolk
edit_uri: edit/main/docs/
repo_name: szvsw/ak-rpi
copyright: Maintained by <a href="https://szvsw.com">Florian</a>.

nav:
  - Home: index.md
  - Reference:
      - Client: reference/client.md
      - NTP Sync: reference/ntp.md
      - Audio: reference/audio.md
      - Player: reference/player.md
      - Utils: reference/utils.md
      - Errors: reference/errors.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            show_source: false
theme:
  name: material
  feature:
    tabs: true
  features:
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/szvsw/ak-rpi
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ak-rpi

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
